<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageProjectUrl>https://github.com/BlackLufus/mqtt</PackageProjectUrl>
    <Title>MqttClient</Title>
    <Copyright>2026</Copyright>
    <Description>A simple mqtt Client to connect to public brokers</Description>
    <RepositoryUrl>https://github.com/BlackLufus/mqtt</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mqtt.Core\Mqtt.Core.csproj" />
  </ItemGroup>
</Project>
